vscode:
    extensions:
        - mgmcdermott.vscode-language-babel
        - aaron-bond.better-comments
        - formulahendry.code-runner
        - streetsidesoftware.code-spell-checker
        - AMiner.codegeex
        - Codeium.codeium
        - GitHub.vscode-codeql
        - vsls-contrib.codetour
        - dalirnet.doctypes
        - joelday.docthis
        - dbaeumer.vscode-eslint
        - zokugun.explicit-folding
        - prantlf.fold-on-open
        - eamodio.gitlens
        - ms-vscode.vscode-typescript-next
        - kimlimjustin.jsdoc-generator
        - runem.lit-plugin
        - ritwickdey.LiveServer
        - bierner.markdown-preview-github-styles
        - mintlify.document
        - CodeQue.codeque
        - mutable-ai.mutable-ai
        - CodeStream.codestream
        - dtsf.octal-back-provider
        - esbenp.prettier-vscode
        - rvest.vs-code-prettier-eslint
        - mblode.pretty-formatter
        - quick-lint.quick-lint-js
        - sketchbuch.vsc-quokka-statusbar
        - pmbenjamin.vscode-snyk
        - SonarSource.sonarlint-vscode
        - sourcegraph.sourcegraph
        - sourcegraph.cody-ai
        - standard.vscode-standard
        - yatki.vscode-surround
        - evgeniypeshkov.syntax-highlighter
        - TabNine.tabnine-vscode
        - hbenl.test-adapter-converter
        - hbenl.vscode-test-explorer
        - Voklen.theme-by-language
        - mattpocock.ts-error-translator
        - hideoo.trailing
        - shardulm94.trailing-spaces
