name: CI Tutor
description: Workflow for a Code Institute Tutor Session
title: "[Tutor]: "
labels: ["tutoring", "triage", "debugging"]
assignees:
  - ipoetdev
body:
  - type: dropdown
    id: project
    attributes:
      label: Which project are you working on?
      multiple: false
      options:
        - P1 HTML CSS
        - P2 Javascript
        - P3 Python
        - P4 Django & Backend
        - P5 Ecommerc
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement Description
      description: Please provide a concise description of your issue?
      placeholder: Short outline of a simple atomic problem or bug
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What Steps for far?
      description: In a stepwise approach, outline the steps you have taken so far ?
      placeholder: Tell us what you have tried!
      value: "A bug happened!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        It is needed to see evidence of the research and debugging that you have carried out so far. | 
        Provided any Google searches, Slack searches, or links to StackOverflow questions or other resources that you have found. |
        Do not enter a tutoring session without spending 15 mins of research.
  - type: input
    id: working-on
    attributes:
      label: Current
      description: What are you working on?
    validations:
      required: true
  - type: input
    id: expected-to-see
    attributes:
      label: Expected Outcome
      description: What do you expect to happen/see?
    validations:
      required: true
  - type: input
    id: actual-as-is
    attributes:
      label: As-is Outcome
      description: What do you see instead?
    validations:
      required: true
   - type: textarea
    id: what-debugging
    attributes:
      label: What debugging efforts?
      description: In further detail, outline the steps you have taken so far ?
      placeholder: What debugging errorts or approaches
    validations:
      required: false
  - type: textarea
    id: console
    attributes:
      label: Browser/Terminal Console 
      description: Please copy the browser/termianal error output..
      render: shell
  - type: checkboxes
    id: prepared
    attributes:
      label: Am I prepared?
      description: Please provide these and we will get back to you within the timeframe communicated by the bot. Failure to provide this information by then will result in this conversation being closed.
      options:
        - label: I agree to follow the Tutor system code of conduct
          required: true
